"""
Global variables related to xcyber360-daemons
"""

LOGCOLLECTOR_DAEMON = 'xcyber360-logcollector'
AGENTLESS_DAEMON = 'xcyber360-agentlessd'
CSYSLOG_DAEMON = 'xcyber360-csyslogd'
REMOTE_DAEMON = 'xcyber360-remoted'
ANALYSISD_DAEMON = 'xcyber360-analysisd'
API_DAEMON = 'xcyber360-apid'
MAIL_DAEMON = 'xcyber360-maild'
SYSCHECK_DAEMON = 'xcyber360-syscheckd'
EXEC_DAEMON = 'xcyber360-execd'
MODULES_DAEMON = 'xcyber360-modulesd'
CLUSTER_DAEMON = 'xcyber360-clusterd'
INTEGRATOR_DAEMON = 'xcyber360-integratord'
MONITOR_DAEMON = 'xcyber360-monitord'
XCYBER365_DB_DAEMON = 'xcyber360-db'
AGENT_DAEMON = 'xcyber360-agentd'


XCYBER365_AGENT_DAEMONS = [LOGCOLLECTOR_DAEMON, SYSCHECK_DAEMON, EXEC_DAEMON, MODULES_DAEMON, AGENT_DAEMON]
XCYBER365_MANAGER_DAEMONS = [LOGCOLLECTOR_DAEMON, AGENTLESS_DAEMON, CSYSLOG_DAEMON, REMOTE_DAEMON, ANALYSISD_DAEMON,
                         API_DAEMON, MAIL_DAEMON, SYSCHECK_DAEMON, EXEC_DAEMON, MODULES_DAEMON, CLUSTER_DAEMON,
                         INTEGRATOR_DAEMON, MONITOR_DAEMON, XCYBER365_DB_DAEMON]

API_DAEMONS_REQUIREMENTS = [API_DAEMON, XCYBER365_DB_DAEMON, EXEC_DAEMON, ANALYSISD_DAEMON, REMOTE_DAEMON, MODULES_DAEMON]
