
# Xcyber360 - Filebeat configuration file
filebeat.modules:
  - module: xcyber360
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/xcyber360-template.json'
setup.template.json.name: 'xcyber360'
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://xcyber360.indexer:9200']
  username: 'admin'
  password: 'SecretPassword'
  ssl.verification_mode: full
  ssl.certificate_authorities: ['/etc/ssl/xcyber360/ca.pem']
  ssl.certificate: '/etc/ssl/xcyber360/filebeat.pem'
  ssl.key: '/etc/ssl/xcyber360/filebeat-key.pem'
