name: ODFE and ELK Single Node Installation Test

on: [push, workflow_dispatch]

jobs: 
  odfe-single-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-7,
          ubuntu-2004,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1

    - name: Install dependencies
      run: |
        cd chif
        bundle config set --local without 'vagrant'
        bundle install

    - name: Install Chef
      uses: actionshub/chef-install@main

    - name: Test ODFE Single Node Installation
      run: |
        cd chif
        kitchen test odfe-single-node-${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml

  elk-single-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-7,
          ubuntu-2004
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1

    - name: Install dependencies
      run: |
        cd chif
        bundle config set --local without 'vagrant'
        bundle install

    - name: Install Chef
      uses: actionshub/chef-install@main

    - name: Test ELK Single Node Installation
      run: |
        cd chif
        kitchen test elk-single-node-${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
